[package]
name = "secret_santa"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.10"
lettre_email = "0.9"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
